version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - results

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=/backend
      - VITE_RESULTS_URL=/results
    depends_on:
      - backend
      - results

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proactive_backend
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:bartar20%40CS@host.docker.internal:21771/proactive?authSource=admin
      - JWT_SECRET=your-secret-key
      - OPENAI_API_KEY=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
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  executor:
    build:
      context: ./executor
      dockerfile: Dockerfile
    container_name: proactive_executor
    environment:
      - BACKEND_URL=http://backend:3000
      - RESULTS_URL=http://results:3001
    depends_on:
      - backend
      - results

  results:
    build:
      context: ./results
      dockerfile: Dockerfile
    container_name: proactive_results
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:bartar20%40CS@host.docker.internal:21771/proactive?authSource=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./results:/app
      - /app/node_modules

  timer:
    build:
      context: ./timer
      dockerfile: Dockerfile
    container_name: proactive_timer
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:3000
      - EXECUTOR_URL=http://executor:8000
      - EXECUTION_INTERVAL_MINUTES=15
    depends_on:
      - backend
      - executor
