services:
  postgres:
    image: postgres:15.3-alpine
    platform: linux/amd64
    container_name: test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# docker run --platform=linux/amd64 --name test-postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:15.3-alpine